<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["user/index", "Go Back"]); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(["user/new", "Create "]); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Search result</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Id</th>
            <th>Username</th>
            <th>Slug</th>
            <th>Password Of Hash</th>
            <th>Reauthentication Of Token</th>
            <th>Email</th>
            <th>Email Of Verified</th>
            <th>Email Of Token</th>
            <th>Email Of Token Of Expires</th>
            <th>Login Of Attempts</th>
            <th>Lockout</th>
            <th>Last Of Login</th>
            <th>Last Of Action</th>
            <th>Is Of Admin</th>
            <th>Created</th>
            <th>Modified</th>
            <th>Language</th>
            <th>Application</th>
            <th>Stripe</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->getItems() as $user): ?>
            <tr>
                <td><?php echo $user['id']; ?></td>
            <td><?php echo $user['username']; ?></td>
            <td><?php echo $user['slug']; ?></td>
            <td><?php echo $user['password_hash']; ?></td>
            <td><?php echo $user['reauthentication_token']; ?></td>
            <td><?php echo $user['email']; ?></td>
            <td><?php echo $user['email_verified']; ?></td>
            <td><?php echo $user['email_token']; ?></td>
            <td><?php echo $user['email_token_expires']; ?></td>
            <td><?php echo $user['login_attempts']; ?></td>
            <td><?php echo $user['lockout']; ?></td>
            <td><?php echo $user['last_login']; ?></td>
            <td><?php echo $user['last_action']; ?></td>
            <td><?php echo $user['is_admin']; ?></td>
            <td><?php echo $user['created']; ?></td>
            <td><?php echo $user['modified']; ?></td>
            <td><?php echo $user['language']; ?></td>
            <td><?php echo $user['application_id']; ?></td>
            <td><?php echo $user['stripe_id']; ?></td>

                <td><?php echo $this->tag->linkTo(["user/edit/" . $user['id'], "Edit"]); ?></td>
                <td><?php echo $this->tag->linkTo(["user/delete/" . $user['id'], "Delete"]); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->getCurrent(), "/", $page->getTotalItems() ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo(["user/search", "First", 'class' => 'page-link', 'id' => 'first']) ?></li>
                <li><?php echo $this->tag->linkTo(["user/search?page=" . $page->getPrevious(), "Previous", 'class' => 'page-link', 'id' => 'previous']) ?></li>
                <li><?php echo $this->tag->linkTo(["user/search?page=" . $page->getNext(), "Next", 'class' => 'page-link', 'id' => 'next']) ?></li>
                <li><?php echo $this->tag->linkTo(["user/search?page=" . $page->getLast(), "Last", 'class' => 'page-link', 'id' => 'last']) ?></li>
            </ul>
        </nav>
    </div>
</div>
